/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Diego G. (https://sketchfab.com/empty_mirror)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/voxel-web-development-50ad959d6c6b4799806c45bfa46ca550
title: Voxel Web Development
*/

import React, { useRef,useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame} from "@react-three/fiber";
export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/computer.gltf')
  const [pageLoaded,setPageloaded] = useState(false)

  function waitforme(milisec) {
    return new Promise(resolve => {
        setTimeout(() => { resolve('') }, milisec);
    })
  }

  async function spin(clock){
    for (let i = 0; i < 10; ++i) {
      const elapsedTime = clock.getElapsedTime()
      group.current.rotation.y = elapsedTime / 0.05
      group.current.rotation.y = elapsedTime / 0.05
      await waitforme(20);
    }
    setPageloaded(true)
  }
    
  useFrame(({ clock }) => {
    spin(clock)
    const elapsedTime = clock.getElapsedTime()
    if(pageLoaded){
      group.current.rotation.y = elapsedTime / 6
      group.current.rotation.y = elapsedTime / 6
    }
  })

  return (
    <group ref={group} {...props} dispose={null} scale={0.1}>
      <group rotation={[-Math.PI / 2, 0,-1.55]} scale={0.7}>
        <group rotation={[Math.PI / 2, 0, 0]} position={[10, -15, -10]}  scale={10}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.palette} />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials['palette.001']} />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_8.geometry} material={materials['palette.002']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/computer.gltf')
