/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: anarki3000 (https://sketchfab.com/anarki3000)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/old-pc-f0dca426be374fba96af9675799f9855
title: Old PC
*/

import React, { useRef,useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame} from "@react-three/fiber";

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/oldcomputer.gltf')
  const [pageLoaded,setPageloaded] = useState(false)

  function waitforme(milisec) {
    return new Promise(resolve => {
        setTimeout(() => { resolve('') }, milisec);
    })
  }



  async function spin(clock){
    for (let i = 0; i < 10; ++i) {
      const elapsedTime = clock.getElapsedTime()
      group.current.rotation.y = elapsedTime / 0.05
      group.current.rotation.y = elapsedTime / 0.05
      await waitforme(20);
    }
    setPageloaded(true)
  }
    
  useFrame(({ clock }) => {
    spin(clock)
    const elapsedTime = clock.getElapsedTime()
    if(pageLoaded){
      group.current.rotation.y = elapsedTime / 6
      group.current.rotation.y = elapsedTime / 6
    }
  })

  return (
    <group ref={group} {...props} dispose={null} scale={0.01}>
      <group rotation={[-Math.PI / 2.02, 0, 0]} scale={1}>
        <group position={[-250, -280, -50]} scale={13}>
          <mesh geometry={nodes.mesh_0.geometry} material={materials.VoxMaterial_64} />
          <mesh geometry={nodes.mesh_1.geometry} material={materials.VoxMaterial_72} />
          <mesh geometry={nodes.mesh_2.geometry} material={materials.VoxMaterial_86} />
          <mesh geometry={nodes.mesh_3.geometry} material={materials.VoxMaterial_87} />
          <mesh geometry={nodes.mesh_4.geometry} material={materials.VoxMaterial_88} />
          <mesh geometry={nodes.mesh_5.geometry} material={materials.VoxMaterial_95} />
          <mesh geometry={nodes.mesh_6.geometry} material={materials.VoxMaterial_96} />
          <mesh geometry={nodes.mesh_7.geometry} material={materials.VoxMaterial_112} />
          <mesh geometry={nodes.mesh_8.geometry} material={materials.VoxMaterial_128} />
          <mesh geometry={nodes.mesh_9.geometry} material={materials.VoxMaterial_136} />
          <mesh geometry={nodes.mesh_10.geometry} material={materials.VoxMaterial_160} />
          <mesh geometry={nodes.mesh_11.geometry} material={materials.VoxMaterial_168} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/oldcomputer.gltf')
