/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: moyicat (https://sketchfab.com/moyicat)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/27c20a0a51124f9c883c080f3323ea04
title: Room 04 /  MagicaVoxel
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame} from "@react-three/fiber";

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/room.gltf')

  useFrame(({ clock }) => {
    const elapsedTime = clock.getElapsedTime()
    group.current.rotation.y = elapsedTime / 6
    group.current.rotation.y = elapsedTime / 6
  })

  return (
    <group ref={group} {...props} dispose={null} scale={0.2}>
      <group rotation={[-Math.PI / 2, 0, 10]} scale={0.1}>
        <group position={[-50, -60, -10]} scale={2}>
          <mesh geometry={nodes.mesh_0.geometry} material={materials['Scene_-_Root']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/room.gltf')
