import type { Metadata } from "next"
import "./globals.css"
import { Nokora } from "next/font/google"
import Nav from "@/components/nav"

const nokora = Nokora({
  variable: "--font-nakora",
  weight: "700",
  subsets: ["khmer"],
  style: "normal",
})

export const metadata: Metadata = {
  title: "Create Next Apsadp",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${nokora.variable} antialiased`}>
        <Nav />
        <main className="pt-12 font-bold leading-[1.4rem]">{children}</main>
      </body>
    </html>
  )
}
