/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: moyicat (https://sketchfab.com/moyicat)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/27c20a0a51124f9c883c080f3323ea04
title: Room 04 /  MagicaVoxel
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/room.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={0.2}>
      <group rotation={[-Math.PI / 3, 0, 10.5]} scale={0.2}>
        <group position={[-20, -30, -6]} scale={1}>
          <mesh geometry={nodes.mesh_0.geometry} material={materials['Scene_-_Root']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/room.gltf')
